name: "Build Release APK (photos)"

on:
    workflow_dispatch: # Allow manually running the action

env:
    FLUTTER_VERSION: "3.24.3"

permissions:
    contents: read # Only need to read the repo

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: mobile

        steps:
            - name: Checkout code and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Setup JDK 17
              uses: actions/setup-java@v1
              with:
                  java-version: 17

            - name: Install Flutter ${{ env.FLUTTER_VERSION }}
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  flutter-version: ${{ env.FLUTTER_VERSION }}
                  cache: true

            - name: Build PlayStore Release APK
              run: |
                  flutter build apk --dart-define=cronetHttpNoPlay=true --flavor playstore

            - name: Upload Release APK
              uses: actions/upload-artifact@v4
              with:
                  name: photos-playstore-release-apk
                  path: mobile/build/app/outputs/apk/playstore/release/app-playstore-release.apk
                  if-no-files-found: error
